spring:
  application:
    name: plugin-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/codex_plugin?useSSL=false&serverTimezone=UTC
    username: root
    password: abc123!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8089
